flisol/apps/inscripcion/urls.py
from django.conf.urls.defaults import patterns, url

urlpatterns = patterns('flisol.apps.inscripcion.views',
	url(r'^$', 'index_view', name = 'vista_principal'),
)

flisol/urls.py
from django.conf.urls import patterns, include, url
import settings

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'flisol.views.home', name='home'),
    # url(r'^flisol/', include('flisol.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
	#url(r'^', include('demo.apps.home.urls')),
    url(r'^', include('flisol.apps.inscripcion.urls')),
    url(r'^media/(?P<path>.*)$','django.views.static.serve',{'document_root':settings.MEDIA_ROOT}),
    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
)

flisol/apps/encuesta/models.py
from django.db import models
from flisol.apps.home.models import UserProfile

class Encuesta(models.Model):
	titulo = models.CharField(max_length=120,verbose_name='Titulo de la Encuesta')
	descripcion = models.TextField(verbose_name='Descripcion de la Encuesta')
	fecha_creacion = models.DateTimeField(auto_now_add=True)
	userProfile = models.ForeignKey(UserProfile,verbose_name='Usuario')

	def __unicode__(self):
		return self.titulo

	class Meta:
		ordering = ['-fecha_creacion']

class Pregunta(models.Model):
	formulacion = models.CharField(max_length=250,verbose_name='Pregunta')
	obligatoria = models.BooleanField(default=True)
	encuesta = models.ForeignKey(Encuesta,verbose_name='Encuesta')

	def __unicode__(self):
		return self.formulacion

	class Meta:
		ordering = ['-encuesta']

class Opcion(models.Model):
	opcion = models.CharField(max_length=300)
	votos = models.IntegerField(null=True,blank=True)
	pregunta = models.ForeignKey(Pregunta,verbose_name='Pregunta')

	def __unicode__(self):
		return self.opcion

	class Meta:
		ordering = ['-pregunta']

class Grupo(models.Model):
	nombre_grupo = models.CharField(max_length=120,verbose_name='Nombre del Grupo')

	def __unicode__(self):
		return self.nombre_grupo

class Asignacion(models.Model):
	fecha_inicio = models.DateTimeField(auto_now_add=True,editable=True,blank=True)
	fecha_finalizacion = models.DateTimeField(auto_now=True,editable=False,blank=True)
	activo = models.BooleanField(default=False)
	encuesta = models.ForeignKey(Encuesta)
	grupo = models.ForeignKey(Grupo)

	class Meta:
		ordering = ['-fecha_inicio']

flisol/apps/home/models.py
from django.db import models
from django.contrib.auth.models import User

class UserProfile(models.Model):
	user = models.OneToOneField(User,verbose_name='Usuario')
	telefono = models.CharField(max_length=15)
	
	def __unicode__(self):
		return self.user.username

class Publicacion(models.Model):

	def url(self,filename):
		ruta = "MultimediaData/Publicacion/%s/%s"%(self.titulo,str(filename))
		return ruta

	def thumbnail(self):
		return '<a href="/media/%s"><img src="/media/%s" width=50px heigth=50px/></a>'%(self.imagen,self.imagen)

	thumbnail.allow_tags = True

	titulo = models.CharField(max_length=120,verbose_name='Titulo de la Publicacion')
	descripcion = models.TextField(verbose_name='Contenido de la publicacion')
	imagen = models.ImageField(upload_to=url,null=True,blank=True)
	fecha_registro = models.DateTimeField(auto_now_add=True)
	fecha_edicion = models.DateTimeField(auto_now=True)
	etiquetas = models.CharField(max_length=225,null=True,blank=True)
	userProfile = models.ForeignKey(UserProfile,verbose_name='Usuario')

	def __unicode__(self):
		return self.titulo

	class Meta:
		ordering = ['-fecha_registro']

flisol/apps/inscripcion/models.py
from django.db import models

class InscritoExpo(models.Model):
	dni = models.CharField(max_length=8,verbose_name='DNI')
	nombres = models.CharField(max_length=120,verbose_name='Nombre(s)')
	apellidos = models.CharField(max_length=120,verbose_name='Apellidos')
	email = models.EmailField(max_length=200,verbose_name='E-Mail')
	telefono = models.CharField(max_length=15,verbose_name='Tel-Cel')
	organizacion = models.CharField(max_length=200)
	pago = models.FloatField(null=True,blank=True)
	fecha_registro = models.DateTimeField(auto_now_add=True)
	fecha_edicion = models.DateTimeField(auto_now=True)
	certificado = models.BooleanField(default=False)
	asistencia = models.BooleanField(default=False)

	def __unicode__(self):
		nombreCompleto = "%s %s"%(self.nombres,self.apellidos)
		return nombreCompleto

	class Meta:
		ordering = ['-fecha_registro']

class Colaborador(models.Model):
	dni = models.CharField(max_length=8,verbose_name='DNI')
	nombres = models.CharField(max_length=120,verbose_name='Nombre(s)')
	apellidos = models.CharField(max_length=120,verbose_name='Apellidos')
	email = models.EmailField(max_length=200,verbose_name='E-Mail')
	telefono = models.CharField(max_length=15,verbose_name='Telefono - Celular')
	organizacion = models.CharField(max_length=200)
	fecha = models.DateTimeField(auto_now_add=True,editable=False,blank=True)
	colabora = models.TextField(verbose_name='En que quiere colaborar')

	def __unicode__(self):
		nombreCompleto = "%s %s"%(self.nombres,self.apellidos)
		return nombreCompleto

	class Meta:
		ordering = ['-fecha']

class Ponente(models.Model):
	dni = models.CharField(max_length=8,verbose_name='DNI')
	nombres = models.CharField(max_length=120,verbose_name='Nombre(s)')
	apellidos = models.CharField(max_length=120,verbose_name='Apellidos')
	email = models.EmailField(max_length=200,verbose_name='E-Mail')
	telefono = models.CharField(max_length=15,verbose_name='Telefono - Celular')
	organizacion = models.CharField(max_length=200)
	fecha = models.DateTimeField(auto_now_add=True,editable=False,blank=True)
	ponencia = models.TextField(verbose_name='Tema de la ponencia')

	def __unicode__(self):
		nombreCompleto = "%s %s"%(self.nombres,self.apellidos)
		return nombreCompleto

	class Meta:
		ordering = ['-fecha']

class Auspiciador(models.Model):
	nombre = models.CharField(max_length=120)
	email = models.EmailField(max_length=200,verbose_name='E-Mail')
	telefono = models.CharField(max_length=15,verbose_name='Telefono - Celular')
	fecha = models.DateTimeField(auto_now_add=True,editable=False,blank=True)
	auspicio = models.TextField(verbose_name='Con que aporto')

	def __unicode__(self):
		return self.nombre

	class Meta:
		ordering = ['-fecha']

class Taller(models.Model):
	nombre = models.CharField(max_length=120,verbose_name='Taller')
	precio = models.FloatField(null=True,blank=True)
	ponente = models.ForeignKey(Ponente)

	def __unicode__(self):
		return self.nombre

	class Meta:
		ordering = ['-nombre']

class InscritoTaller(models.Model):
	dni = models.CharField(max_length=8,verbose_name='DNI')
	nombres = models.CharField(max_length=120,verbose_name='Nombre(s)')
	apellidos = models.CharField(max_length=120,verbose_name='Apellidos')
	email = models.EmailField(max_length=200,verbose_name='E-Mail')
	telefono = models.CharField(max_length=15,verbose_name='Tel-Cel')
	organizacion = models.CharField(max_length=200)
	pago = models.FloatField(null=True,blank=True)
	fecha_registro = models.DateTimeField(auto_now_add=True)
	fecha_edicion = models.DateTimeField(auto_now=True)
	certificado = models.BooleanField(default=False)
	asistencia = models.BooleanField(default=False)
	taller = models.ForeignKey(Taller)

	def __unicode__(self):
		nombreCompleto = "%s %s"%(self.nombres,self.apellidos)
		return nombreCompleto

	class Meta:
		ordering = ['-fecha_registro']

flisol/apps/inscripcion/forms.py
from django import forms
from flisol.apps.inscripcion.models import InscritoExpo

class addInscritoForm(forms.ModelForm):
	class Meta:
		model 	= InscritoExpo

flisol/apps/encuesta/views.py
# Create your views here.

flisol/apps/home/views.py
# Create your views here.

flisol/apps/inscripcion/views.py
from django.shortcuts import render_to_response
from django.template import RequestContext
from flisol.apps.inscripcion.forms import addInscritoForm
from flisol.apps.inscripcion.models import InscritoExpo
from django.http import HttpResponseRedirect

def index_view(request):
	info = "iniciado"
	if request.method == "POST":
		form = addInscritoForm(request.POST,request.FILES)
		if form.is_valid():
			add = form.save(commit=False)
			add.save() # Guardamos la informacion
			info = "Guardado satisfactoriamente"
			return HttpResponseRedirect('')
	else:
		form = addInscritoForm()
	ctx = {'form':form, 'informacion':info}
	return render_to_response('page/index.html',ctx,context_instance = RequestContext(request))

flisol/templates/base.html
<!doctype html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
	<title>FLISOL 2014 - TACNA</title>
	<link rel="stylesheet" href="/media/css/normalize.css">
	<link rel="stylesheet" href="/media/css/estilos.css">
	<link href='http://fonts.googleapis.com/css?family=Droid+Serif:700' rel='stylesheet' type='text/css'>
	<link href='http://fonts.googleapis.com/css?family=Droid+Sans' rel='stylesheet' type='text/css'>
</head>
<body>
<header>
	<div class="centrar">
		<figure>
			<img src="/media/imgs/logo_flisol.png" alt="">
		</figure>
		<h1>
			10 Festival Latinoamericano de Instalación de Software Libre
		</h1>
		<p>Sede - Tacna</p>
	</div>
</header>
<nav>
	<div class="centrar">
		<ul>
			<a href="#" class="flisol"><img src="/media/imgs/flisol.png" alt="" height="45px" width="85px"></a>
			<li><a href="#que-es" data-scroll data-speed="770" data-easing="easeOutQuint" data-url="false">¿Qué es FLISOL?</a></li>
			<li><a href="#actividades" data-scroll data-speed="770" data-easing="easeOutQuint" data-url="false">Actividades</a></li>
			<li><a href="#cronograma" data-scroll data-speed="770" data-easing="easeOutQuint" data-url="false">Cronograma</a></li>
			<li><a href="#ubicacion" data-scroll data-speed="770" data-easing="easeOutQuint" data-url="false">Ubicación</a></li>
			<li><a href="#auspiciador" data-scroll data-speed="770" data-easing="easeOutQuint" data-url="false">Auspiciadores</a></li>
		</ul>
		<a href="" class="inscribirse">Inscríbete (es gratis)</a>
	</div>
</nav>
<div class="agrupado">
 	<section class="que-es" id="que-es">
 		<div class="centrar">
 			<h2>¿Qué es FLISOL?</h2>
	 		<p>El Festival Latinoamericano de Instalación de Software Libre (FLISOL) es actualmente el evento de instalación y difusión de Software Libre más grande en el mundo. Se realiza desde el año 2005 en diversos países de Latinoamérica, habiéndose extendido a otras regiones como España y Estados Unidos.</p>
	 		<p>El principal objetivo de FLISOL es promover el uso del software libre, dando a conocer al público en general su filosofía, alcances, avances y desarrollo.</p>
	 		<p>Cada año, en una fecha simultánea por acuerdo internacional, las diversas comunidades locales de software libre (en cada país y ciudad participante) organizan eventos en los que se instala, de manera gratuita y totalmente legal, programas de software libre en las computadoras que llevan los asistentes.</p>
	 		<div class="frase">
	 			<figure>
	 				<img src="/media/imgs/stallman.png" alt="">
	 			</figure>
	 			<p>Beethoven era un buen compositor porque utilizaba ideas nuevas en combinación con ideas antiguas. Nadie, ni siquiera Beethoven podría inventar la música desde cero. Es igual con la informática.  (Por Richard Stallman)</p>
	 		</div>
 		</div>
 	</section>
 	<div class="centrar">
 		<section class="separar">
 			<figure>
 				<img src="/media/imgs/estrella.png" alt="">
 			</figure>
 		</section>
 	</div>
 	<section class="actividades" id="actividades">
 		<div class="centrar">
 			<h2>Actividades</h2>
 			<div class="actividades">
 				<div class="actividad">
 					<figure>
 						<img src="/media/imgs/conferencias.png" alt="">
 					</figure>
 					<div class="descripcion">
 						<h3>Conferencias</h3>
 						<p>Conferencias, charlas y talleres dirigidos por personas que han implementado y han hecho uso del software libre. </p>
 					</div>
 				</div>

 				<div class="actividad">
 					<figure>
 						<img src="/media/imgs/instalacion.png" alt="">
 					</figure>
 					<div class="descripcion">
 						<h3>Instalaciones</h3>
 						<p>Habrá espacios donde los visitantes podrán acercarse
						con su computadoras personales a instalar software libre
						</p>
 					</div>
 				</div>

 				<div class="actividad">
 					<figure>
 						<img src="/media/imgs/cd-dvd.png" alt="">
 					</figure>
 					<div class="descripcion">
 						<h3>CD's y DVD's</h3>
 						<p>Podrán obtener CD’s y DVD’s con software libre en los stands dedicados a Distribuciones GNU/LINUX y Software Libres mas populares.
						</p>
 					</div>
 				</div>

 				<div class="actividad">
 					<figure>
 						<img src="/media/imgs/feria.png" alt="">
 					</figure>
 					<div class="descripcion">
 						<h3>Feria Tecnológica</h3>
 						<p>Stands donde podrás ver proyectos en los cuales se utiliza el sofware libre.  Encontrarás gran cantidad de información muy útil.
						</p>
 					</div>
 				</div>

 				<div class="actividad">
 					<figure>
 						<img src="/media/imgs/conversatorio.png" alt="">
 					</figure>
 					<div class="descripcion">
 						<h3>Conversatorio</h3>
 						<p>Conversatorios sobre el impacto del software libre en la educación, gestión pública y pequeña y mediana empresas.
						</p>
 					</div>
 				</div>

 			</div>
 		</div>
 	</section><!-- Fin Actividades -->

 	<div class="centrar">
 		<section class="separar">
 			<figure>
 				<img src="/media/imgs/estrella.png" alt="">
 			</figure>
 		</section>
 	</div>

 	<section class="cronograma" id="cronograma">
 		<div class="centrar">
 			<h2>Cronograma</h2>
 			<p>Por la mañana</p>
 			<div class="cronograma-actividad">
 				<div class="hora">09:45 - 10:00</div>
 				<div class="detalle">
 					<span class="titulo">Bienvenida al FLISOL 2014</span>
 					<span class="detalle">Palabras de apertura por el Coordinador de Sede - Alan Robert Quispe Acho</span>
 				</div>
 			</div>
 			<div class="cronograma-actividad">
 				<div class="hora">10:00 - 10:30</div>
 				<div class="detalle">
 					<span class="titulo">Charla: Alternativas de Software Libre para la Sociedad y Oportunidades de Investigación y desarrollo tecnológico </span>
 					<span class="detalle">Charla brindada por Jorge Antonio Linares Vera (Fundador de la CSL BasadrinuX) </span>
				</div>
 			</div>
 			<div class="cronograma-actividad">
 				<div class="hora">10:30 - 11:30</div>
 				<div class="detalle">
 					<span class="titulo">Hardware Libre y Arduino para la Educación</span>
 					<span class="detalle">Neyder Achahuanco Apaza (Escuelab PUNO)</span>
 				</div>
 			</div>
			<div class="cronograma-actividad">
 				<div class="hora">11:30 - 12:00</div>
 				<div class="detalle">
 					<span class="titulo">Implantando Radio Online con Software Libre</span>
 					<span class="detalle">Jean Carlos Anchapuri Mamani (Co-Fundador de la CSL BasadrinuX)</span>
 				</div>
 			</div>
 			<div class="cronograma-actividad">
 				<div class="hora">12:00 - 13:00</div>
 				<div class="detalle">
 					<span class="titulo">Herramientas de Software Libre para el desarrollo de aplicaciones web</span>
 					<span class="detalle">Charla a cargo de Eduar Ruben Apaza Yañez </span>
 				</div>
 			</div>
 			<p>Por la tarde</p>
 			<div class="cronograma-actividad">
 				<div class="hora">15:30 - 16:30</div>
 				<div class="detalle">
 					<span class="titulo">Diseño de Juegos, introducción al esarrollo con Cocos 2D</span>
 					<span class="detalle">Palabras de Marvin Daniel Galvez Pilco (Tacna Valley)</span>
 				</div>
 			</div>
 			<div class="cronograma-actividad">
 				<div class="hora">16:30 - 17:30</div>
 				<div class="detalle">
 					<span class="titulo">Monitoreo de red y servicios con Gnu/Linux</span>
 					<span class="detalle">Charla a cargo del Ing. Renzo Taco (ITS PERU)</span>
 				</div>
 			</div>
 			<div class="cronograma-actividad">
 				<div class="hora">17:30 - 18:30</div>
 				<div class="detalle">
 					<span class="titulo">De MySQL a MariaDB</span>
 					<span class="detalle">Charla a cargo del Ing. Ricardo Inquilla (Eureka)</span>
 				</div>
 			</div>
 			<div class="cronograma-actividad">
 				<div class="hora">18:30 - 19:30</div>
 				<div class="detalle">
 					<span class="titulo">Software libre para mypes</span>
 					<span class="detalle">Charla a cargo del Ing. Gianfranco Malaga Tejada (Docente UNJBG)</span>
 				</div>
 			</div>

 		</div>
 	</section>

 	<div class="centrar">
 		<section class="separar">
 			<figure>
 				<img src="/media/imgs/estrella.png" alt="">
 			</figure>
 		</section>
 	</div>

	<section class="ubicacion" id="ubicacion">
		<div class="centrar">
			<h2>Ubicación</h2>
			<p>El Décimo Festival Latinoamericano de Instalación de Software Libre - FLISOL 2014 se llevará a cabo en</p>
		</div>
		<div id="mapa"></div>
	</section>

	<div class="centrar">
 		<section class="separar">
 			<figure>
 				<img src="/media/imgs/estrella.png" alt="">
 			</figure>
 		</section>
 	</div>

	<section class="auspiciador" id="auspiciador">
		<div class="centrar">
			<h2>Auspiciadores</h2>
			<p>El Décimo Festival Latinoamericano de Instalación de Software Libre - FLISOL 2014 llega gracias al gentil apoyo
de las siguientes empresas:</p>
			<div class="empresas">
				<figure>
					<img src="/media/imgs/auspiciadores/auspicios.svg" width="800px" height="600px" alt="">
				</figure>
			</div>
		</div>
	</section>
	<footer>
		<div class="centrar">
			<figure>
				<img src="/media/imgs/cc.png" alt="">/media/
			</figure>
			<figure>
				<img src="/media/imgs/gpl.png" alt="">
			</figure>
			<div class="contenido">
				<p>El contenido de la página está bajo la licencia de Creative Commons Reconocimiento Compartir Igual 3.0 Unported.</p>
				<p>El código fuente de la página está disponible en <a href="">Github</a> bajo la <a href="">GNU Public License 3.0</a> </p>
			</div>
		</div>
	</footer>
</div>

<div class="efectocomprar">
		<div class="efecto"></div>
		<div class="form">
				<!--<form id="form">
					<h4 id="h4">Ingresa tus Datos personales</h4>
					<input type="text" placeholder="Nombres y Apellidos">
					<input type="text" placeholder="Email">
					<p>Para los que deseen certificado, éste tendrá un valor de S/ 10.00 nuevos soles</p>
					<input type="checkbox" value="certificado">¿Con certificado?
					<input type="submit" value="Incribirme">
				</form>-->
				<form id="form" action="." method="POST" enctype="multipart/form-data">
			{% csrf_token %}
    		<fieldset>
			<div class="clearfix">
				{{ form.subject.errors}}
				<label for="id_nombres" >Nombres</label>
				{{ form.nombres }}
			</div>
			<div class="clearfix">
				{{ form.subject.errors}}
				<label for="id_apellidos" >Apellidos</label>
				{{ form.apellidos}}
			</div>
			<div class="clearfix">
				{{ form.subject.errors}}
				<label for="id_dni" >DNI</label>
        		{{ form.dni }}
			</div>
			<div class="clearfix">
				{{ form.subject.errors}}
				<label for="id_email" >Email</label>
        		{{ form.email }}
			</div>
			<div class="clearfix">
				{{ form.subject.errors}}
				<label for="id_telefono" >Teléfono</label>
        		{{ form.telefono }}
			</div>
			<div class="clearfix">
				{{ form.subject.errors}}
				<label for="id_organizacion">Organización/C. Estudio/Empresa</label>
				{{ form.organizacion }}
			</div>
			<div class="certificado">
				{{ form.subject.errors}}
				<label for="id_certificado">Certificado: (S/. 20)</label>
				{{ form.certificado }}
			</div>
			<input type="submit" name="mysubmit" id="mysubmit" value="Realizar Inscripción">
    <button type="reset" class="btn btn-small btn-primary">Limpiar</button>

		</fieldset>

		<!-- RESULTADO-->
			<div id="result"></div>
		</form>
		</div>
</div>

<script src="//ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
<script type="text/javascript" src="http://maps.google.com/maps/api/js?sensor=true"></script>
<script src="/media/js/gmaps.js"></script>
<script src="/media/js/smooth-scroll.js"></script>

<script>
		$('.inscribirse').click(function(e){
			e.preventDefault();
			$('.efectocomprar').css("display","block");
			console.log("Click aqui");
		});
		$('.efecto').click(function(){
			$('.efectocomprar').css("display","none");
			console.log("Click");
		});
</script>
<script>
	$(document).ready(function(){
	 	var map = new GMaps({
	    el: '#mapa',
	    lat: -18.025022,
	    lng: -70.250504,
	    zoom: 17,
	    zoomControl : false,
	    zoomControlOpt: {
	        style : 'SMALL',
	        position: 'TOP_LEFT'
	    },
	    panControl : false,
 	 	});

 	 	map.addMarker({
      	lat: -18.025022,
      	lng: -70.250504,
      	title: 'Universidad Nacional Jorge Basadre Grohmann',
      	infoWindow: {
        content: '<p>Universidad Nacional Jorge Basadre Grohmann</p>' }
    	});

	});
</script>
<script>
var mn = $('nav');
$(window).scroll(function(){
	if( $(this).scrollTop() > 360 ){
		mn.addClass('nav-scrolled');
	}else{
		mn.removeClass('nav-scrolled');
	}
});
</script>
</body>
</html>

flisol/templates/page/index.html
{% extends 'base.html' %}
{% block title %} Agregar Producto {% endblock %}
{% block content %}
{% endblock %}